#
# QualiCharge Open Data package
#
[project]
name = "qualicharge-opendata"
version = "0.1.0"
requires-python = "~=3.12.0"
dependencies = [
  "data7==0.13.2",
  "psycopg[binary,pool]==3.2.12",
]

[dependency-groups]
dev = [
    "honcho==2.0.0",
]

[tool.uv]
link-mode = "copy"
